apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secops-secrets-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["pods","pods/log","configmaps"]
    verbs: ["get","list","watch"]
