apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: domain-admin
  namespace: tenant
rules:
  - apiGroups: ["apps"]
    resources: ["deployments","statefulsets","daemonsets","replicasets"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["jobs","cronjobs"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods","pods/log","services","endpoints","persistentvolumeclaims","configmaps"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses","networkpolicies"]
    verbs: ["*"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["*"]
